### ISSUE TITLE
Document Development Process

### ISSUE THREAD

**Issue by david-morris** [aboveyunhai/chakra-dayzed-datepicker#15]
It would be easier to work on this project if it was documented in the README how to get from a git repo of this package to an installed forked version.

For example, I just added `david-morris/chakra-dayzed-datepicker` to my yarn classic project's `package.json`, installed, and ran `npm install && npm run build` in the `node_modules/chakra-dayzed-datepicker` directory.  My changes were present, but the chakra theme was broken on the datepicker component.  If I knew the correct way to install that, I would have been more confident in my PR.

**Comment by aboveyunhai** [comment]
Technically, `package.json` is the development document for many simple libs.
