### ISSUE TITLE
decouple the Calendar Panel

### ISSUE THREAD

**Issue by aboveyunhai** [aboveyunhai/chakra-dayzed-datepicker#16]
export the Calendar Panel so it doesn't have to be tied with the input.

**Comment by dougcalc** [comment]
I agree that this would be handy. I'm trying to style the datepicker input around an InputGroup and InputLeftAddon, but it doesnt work when the input is wrapped in Popover internally :)

**Comment by L2Develop96** [comment]
Is there anyway to do this? Not possible I guess right

**Comment by aboveyunhai** [comment]
close by #49
