### ISSUE TITLE
bug - SingleDatepicker - popover not opens in the selected date month

### ISSUE THREAD

**Issue by wellDan28** [aboveyunhai/chakra-dayzed-datepicker#18]
when clicking on `SingleDatepicker` where the date is already set, the popover will open on today calendar page.
I would expect that it will be open on the provided date.
(after choosing another date it behave as expected)

**Comment by aboveyunhai** [comment]
I think I can make it as an option so you can control which behavior you want to have.

**Comment by aboveyunhai** [comment]
@wellDan28 feel free to test PR to see if it resolves the issue.

**Comment by wellDan28** [comment]
@aboveyunhai this pr resolve the issue, thanks, really appreciate it!
