### ISSUE TITLE
How to close popover after choosing date/range dates?

### ISSUE THREAD

**Issue by bielas** [aboveyunhai/chakra-dayzed-datepicker#24]

**Comment by aboveyunhai** [comment]
click the input again or outside of the panel.
Do you have any specific use case where you can't do either way.

**Comment by svitekpavel** [comment]
@aboveyunhai use case - you want to select range - select 1st date (keep open), select 2nd date - close now, as the selection is complete. I consider this a default behaviour for for range selection, so I would implement a prop `keepOpen: boolean` to allow people who want to overwrite the behaviour. Does this make sense?

**Comment by aboveyunhai** [comment]
> @aboveyunhai use case - you want to select range - select 1st date (keep open), select 2nd date - close now, as the selection is complete. I consider this a default behaviour for for range selection, so I would implement a prop `keepOpen: boolean` to allow people who want to overwrite the behaviour. Does this make sense?

make sense, let me take a look at it. basically an `select on close` for range picker, so the behavior keeps consistent with the single date picker
