### ISSUE TITLE
Display short name of days as the input label/value

### ISSUE THREAD

**Issue by cedrvanh** [aboveyunhai/chakra-dayzed-datepicker#39]
I'm trying to display the short names of days as the label/value of the input, but it doesn't seem to work. If I look at the formatting docs of date-fns I should be able to pass 'ddd' to dateFormat of the config object. Doing this just prepends a 0 to the current day for each 'd' added.

Code:
```
<SingleDatepicker
    ...props
    configs={{
        dateFormat: 'ddd - dd/MM',
        monthNames: MonthNamesShort,
        dayNames: WeekdayNamesShort,
    }}
/>
```

Formatting like this gives me this result:
<img width="256" alt="Screenshot 2023-01-19 at 12 33 47" src="https://user-images.githubusercontent.com/26408655/213432092-1747992b-cc25-4b03-9aca-3c9b0aaa91ac.png">

The expected result would be: **Thu - 19/01**

**Comment by aboveyunhai** [comment]
Based on `date-fns`, you are looking for `EEE - dd/MM` .

**Comment by cedrvanh** [comment]
@aboveyunhai you're right! thank you
