### ISSUE TITLE
using `minDate`, date button do not have disabled style

### ISSUE THREAD

**Issue by jeromevvb** [aboveyunhai/chakra-dayzed-datepicker#40]
Hi everyone, 
I have set a `minDate` : Tue Feb 28 2023 , days before minDate are not active but do not have any `disabled` styles.
I've tried to force it myself with the propsConfigs but it does not work.

Buttons keep whiteColor

<img width="427" alt="Screenshot 2023-01-29 at 2 23 12 PM" src="https://user-images.githubusercontent.com/7522096/215311556-d9ef6c6a-32c9-4ba7-b324-5ad03584be90.png">

```
propsConfigs={{
                inputProps: { size: 'lg' },
                dayOfMonthBtnProps: {
                  defaultBtnProps: {
                    _hover: {
                      background: 'primary.500'
                    },
                    _disabled: {
                      opacity: 0.4,
                    }
                  },
                  selectedBtnProps: {
                    color: 'white',
                    bgColor: 'primary.500'
                  }
                }
              }}
```

Any ideas?Thank you
Version:
chakra-ui/react: ^2.4.7
chakra-dayzed-datepicker: ^0.2.6

**Comment by jeromevvb** [comment]
https://github.com/aboveyunhai/chakra-dayzed-datepicker/blob/main/src/components/dayOfMonth.tsx#L87

i'm thinking this should be `isDisabled` instead of `disabled` according to the Button docs

**Comment by aboveyunhai** [comment]
> https://github.com/aboveyunhai/chakra-dayzed-datepicker/blob/main/src/components/dayOfMonth.tsx#L87
> 
> i'm presuming this should be `isDisabled` instead of `disabled` according to the Button docs

You are right, the `disabled` existed before v2, and it seems like it was removed in v2 at some point.

**Comment by aboveyunhai** [comment]
npm@0.2.7 is out. @jeromevvb  let me know id the issue still persists

**Comment by jeromevvb** [comment]
@aboveyunhai works perfectly, great job!
