### ISSUE TITLE
Open RangeDatepicker in chakra ui modal

### ISSUE THREAD

**Issue by MezianeKhalil** [aboveyunhai/chakra-dayzed-datepicker#43]
![Untitled](https://user-images.githubusercontent.com/67861260/218302281-16522023-9acb-4a52-88da-57dfebecb0b0.png)

**Comment by aboveyunhai** [comment]
can you provide a minimal sample how your modal and datepicker is combined in codesandbox?
There are multiple problems (index, position, clipping, etc) need to be addressed depending on your code.
