### ISSUE TITLE
Disable individual dates

### ISSUE THREAD

**Issue by JollyGrin** [aboveyunhai/chakra-dayzed-datepicker#44]
I'm trying to create an event calendar that allows people to select dates. Yet once someone selects a date, I need to disable it for others.

Thus how do I pass a disabled prop to individual dates?

**Comment by JollyGrin** [comment]
Great! That would be very useful!

**Comment by aboveyunhai** [comment]
close by #49

**Comment by natezhengbne** [comment]
Hi @aboveyunhai,
I noticed you've added a `disabledDates` field to disable specific days. 
However, it seems this field doesn't support disabling weekends on the calendar dynamically. To achieve this, consider implementing a similar approach to react-select, using a callback function like filterDate to dynamically disable days at runtime.

**Comment by aboveyunhai** [comment]
> Hi @aboveyunhai, I noticed you've added a `disabledDates` field to disable specific days. However, it seems this field doesn't support disabling weekends on the calendar dynamically. To achieve this, consider implementing a similar approach to react-datepicker, using a callback function like `filterDate` to dynamically disable days at runtime.
> 
> Would you be interested in receiving a pull request for this feature?

Feel free to create the PR! just wonder why the `disabledDates` doesn't work in your case 
doesn't the following work?
```ts

const disabledDates = useMemo(() => { 
   // your filter logic here, which is the same as the filterDate function
  // put dynamic dates into the Set
   return new Set();
}, [])

disabledDates = {disabledDates}
```

**Comment by natezhengbne** [comment]
Hi @aboveyunhai,

**Background**: I'm working on a timelog system where weekends should be disabled for selection on the current calendar panel.

_To dynamically disable weekends on the calendar:_
It seems there's no way to directly access the current date range within the component. However, I can still pass all weekend days of the current month to the disabledDates prop. While this approach might not be the most efficient, it should achieve the desired result.

I'm considering adding a callback function type to the disabledDate prop. This function would accept a date object and return true if the date should be disabled or false if it should be enabled.
