### ISSUE TITLE
Change fontWeight on weekDays and monthNames

### ISSUE THREAD

**Issue by Qadra42** [aboveyunhai/chakra-dayzed-datepicker#55]
Thanks for this useful component!
![Screenshot 2023-06-14 at 18 39 26](https://github.com/aboveyunhai/chakra-dayzed-datepicker/assets/79875131/1f2cc9db-aaf2-4e1b-9243-55696aca3967)

![Screenshot 2023-06-14 at 18 41 18](https://github.com/aboveyunhai/chakra-dayzed-datepicker/assets/79875131/626ddf83-36c4-47c8-ac51-a10461fcf91a)

I had to do some tricky workaround in order to change this fontWeight. I think it could be a nice improvement by adding this as propsConfig.

**Comment by elizabethboterf** [comment]
How did you do it? I am trying to change the font weight and size of the week days and month/year as well.

**Comment by aboveyunhai** [comment]
> How did you do it? I am trying to change the font weight and size of the week days and month/year as well.

solved by https://github.com/aboveyunhai/chakra-dayzed-datepicker/pull/57
