### ISSUE TITLE
Ability edit VStack borderWidth

### ISSUE THREAD

**Issue by mirror-ru** [aboveyunhai/chakra-dayzed-datepicker#61]
Add ability to edit properties of this block. I need to make borderWidth: 0.

https://github.com/aboveyunhai/chakra-dayzed-datepicker/blob/main/src/components/calendarPanel.tsx#L93C13-L93C24

![image](https://github.com/aboveyunhai/chakra-dayzed-datepicker/assets/80034626/fb4014a1-f3ef-4ea6-8ffe-d1b3a8fb67d1)

Example with borderWidth: 0

![image](https://github.com/aboveyunhai/chakra-dayzed-datepicker/assets/80034626/03913f59-98d2-4380-bf57-e42902e2b0c2)

**Comment by mirror-ru** [comment]
Current with borderWidth: '1px':
![image](https://github.com/aboveyunhai/chakra-dayzed-datepicker/assets/80034626/e0d143f7-c873-45f1-92ee-da198b4fd3c1)

**Comment by mirror-ru** [comment]
Can I get an answer?

**Comment by aboveyunhai** [comment]
> Can I get an answer?

Yep. There will be a PR for it later today. Just need to be outside of my regular work hour.

**Comment by aboveyunhai** [comment]
npm@0.2.10 is out.
@mirror-ru  this should solve your question, there are other props inside calendar panel you can use, just check the doc or source code
```ts    
 calendarPanelProps: {
    contentProps: {
      borderWidth: 0,
    },
  }
```

**Comment by mirror-ru** [comment]
It works, thanks!
