### ISSUE TITLE
change positioning of calendar panels

### ISSUE THREAD

**Issue by elizabethboterf** [aboveyunhai/chakra-dayzed-datepicker#65]
Hi!

I am using your RandeDatePicker in a component on the right side of my page. The calendar panels overflow off screen and the user can not select dates from the second panel. I have tried changing the zIndex and the placement props with 
propsConfigs={{
      popoverCompProps:{ 
        popoverContentProps: {
           placement: 'left-start',
           zIndex: 300
      }
    }
}}

I also tried this with popoverBodyProps which also did not work. If we can't change the placement, Is there a way to change the behavior of the overflow? Maybe switch to a column instead of a row? Or is there a way to do a RangeDatePicker with just one calendar panel? 

Appreciate the help, thanks!

**Comment by aboveyunhai** [comment]
@elizabethboterf  it's hard to understand how it looks like without a video. The best way you can do is to create a codesandbox demo to replicate the issue, The problem could be upstream issue from Chakra UI without knowing at the code.

**Comment by elizabethboterf** [comment]
Ok, I recreated the problem on this code sandbox.

https://codesandbox.io/p/sandbox/loginplay-forked-v42yn3?file=%2Fsrc%2FChakraDatePicker.js

I think the main issue is with the controller. 
Do you know of a work around while still using the controller?

**Comment by aboveyunhai** [comment]
@elizabethboterf   
is `usePortal={true}` what you want ? The overflow style of container cuts off the component.

**Comment by FarhanAbdulQayyum** [comment]
@aboveyunhai 
Yes `usePortal={true}` does fix the issue.
I have tested with `usePortal={true}` on the same sandbox.

![datepicker](https://github.com/aboveyunhai/chakra-dayzed-datepicker/assets/31679337/dba9b203-24ac-4d23-87f5-c0f24ebb9b1a)
