### ISSUE TITLE
Always keep the date picker open

### ISSUE THREAD

**Issue by L2Develop96** [aboveyunhai/chakra-dayzed-datepicker#67]
I want to keep the date picker always open and always displayed without the input field. I've set the input field visibility to none, but when i click around the datepicker closes.

Is there anyway, to keep the  component always open and displayed?

**Comment by aboveyunhai** [comment]
@L2Develop96  You can utilize the calendar panel without using the input at all

check the calendar example: https://aboveyunhai.github.io/chakra-dayzed-datepicker/ 

https://github.com/aboveyunhai/chakra-dayzed-datepicker/blob/main/example/index.tsx#L339
