### ISSUE TITLE
make it possible to change selected color

### ISSUE THREAD

**Issue by JohnDeved** [aboveyunhai/chakra-dayzed-datepicker#7]
setting selectedBg to a dark color makes it impossible to read the selected text. and there seems to be no way to change selectedColor

**Comment by JohnDeved** [comment]
https://github.com/aboveyunhai/chakra-dayzed-datepicker/blob/a5ae792600b3173b146f3fb23060102217ed351a/src/components/dayOfMonth.tsx#L24-L25

there needs to be a line added here that sets a color variable and passes it to the Button component

**Comment by JohnDeved** [comment]
its seems you are only able to change text color of all buttons, not only the selected ones

**Comment by aboveyunhai** [comment]
good catch, will take a look at it

**Comment by JohnDeved** [comment]
here is a snipped on how i used it @aboveyunhai 

```tsx
      <RangeDatepicker
        selectedDates={selectedDates}
        onDateChange={setSelectedDates}
        propsConfigs={{
          dayOfMonthBtnProps: {
            borderColor: 'primary.500',
            selectedBg: 'ruefaGray.600',
            // color: 'white',
            _hover: { bg: 'ruefaGray.500' },
          },
        }}
      />
```

**Comment by aboveyunhai** [comment]
@JohnDeved  it seems like we need a dedicated `props` for selected button, let me come out a more general solution over the weekend so it's not limited to background but every styles you want to modify on the selected btn

**Comment by JohnDeved** [comment]
@aboveyunhai may I give a suggestion?

```jsx
    <Button
	 // [...]
      {...(selected || isInRange ? customBtnSelectedProps : customBtnProps)}
    >
```

this way you have full control of all selected styles of the button

**Comment by aboveyunhai** [comment]
> @aboveyunhai may I give a suggestion?
> 
> ```js
>     <Button
>        // [...]
>       {...(selected || isInRange ? customBtnSelectedProps : customBtnProps)}
>     >
> ```
> 
> this way you have full control of all selected styles of the button

u got what I mean, just want to make sure we don't accidentally override something that should stay the same.
