### ISSUE TITLE
Module not found: Error: Can't resolve 'date-fns' in chakra-dayzed-datepicker/dist

### ISSUE THREAD

**Issue by pratiks-wellsky** [aboveyunhai/chakra-dayzed-datepicker#75]
When trying to build with next, It's showing Can't resolve 'date-fns'

**Comment by aboveyunhai** [comment]
Please read the doc, you need to install the dependencies
![image](https://github.com/aboveyunhai/chakra-dayzed-datepicker/assets/35160613/edd2bfdc-5c4e-44c5-8190-a859e1c680b1)
