### ISSUE TITLE
NPM Package version

### ISSUE THREAD

**Issue by diegotraid** [aboveyunhai/chakra-dayzed-datepicker#79]
Although the latest version seems to be 0.2.10 (in package.json and on the [NPMjs](https://www.npmjs.com/package/chakra-dayzed-datepicker) I see some discrepancies on the source code when installing via NPM.

Am I missing something or maybe the latest changes weren't published?

**Comment by aboveyunhai** [comment]
@diegotraid  yes, let me publish the v0.3 lately this weekend. fwiw, it contains lots of breaking changes (fix).

**Comment by diegotraid** [comment]
Great @aboveyunhai ! Looking forward for it!
